apiVersion: opsgenie.upbound.io/v1alpha1
kind: EmailIntegration
metadata:
  annotations:
    meta.upbound.io/example-id: opsgenie/v1alpha1/emailintegration
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    emailUsername: fahri
    name: genieintegration-name

---

