apiVersion: opsgenie.upbound.io/v1alpha1
kind: Escalation
metadata:
  annotations:
    meta.upbound.io/example-id: opsgenie/v1alpha1/escalation
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: genieescalation-%s
    rules:
    - condition: if-not-acked
      delay: 1
      notifyType: default
      recipient:
      - idSelector:
          matchLabels:
            testing.upbound.io/example-name: test
        type: user

---

