apiVersion: opsgenie.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: opsgenie/v1alpha1/team
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: This team deals with all the things
    member:
    - id: ${opsgenie_user.first.id}
      role: admin
    - id: ${opsgenie_user.second.id}
      role: user
    name: example

---

