/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ApiIntegrationObservation struct {

	// The id of the responder.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ApiIntegrationParameters struct {

	// This parameter is for configuring the write access of integration. If write access is restricted, the integration will not be authorized to write within any domain. Default: true.
	// +kubebuilder:validation:Optional
	AllowWriteAccess *bool `json:"allowWriteAccess,omitempty" tf:"allow_write_access,omitempty"`

	// This parameter is for specifying whether the integration will be enabled or not. Default: true
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Headers map[string]*string `json:"headers,omitempty" tf:"headers,omitempty"`

	// If enabled, the integration will ignore recipients sent in request payloads. Default: false.
	// +kubebuilder:validation:Optional
	IgnoreRespondersFromPayload *bool `json:"ignoreRespondersFromPayload,omitempty" tf:"ignore_responders_from_payload,omitempty"`

	// Name of the integration. Name must be unique for each integration.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Owner team id of the integration.
	// +crossplane:generate:reference:type=Team
	// +kubebuilder:validation:Optional
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`

	// User, schedule, teams or escalation names to calculate which users will receive the notifications of the alert.
	// +kubebuilder:validation:Optional
	Responders []ApiIntegrationRespondersParameters `json:"responders,omitempty" tf:"responders,omitempty"`

	// If enabled, notifications that come from alerts will be suppressed. Default: false.
	// +kubebuilder:validation:Optional
	SuppressNotifications *bool `json:"suppressNotifications,omitempty" tf:"suppress_notifications,omitempty"`

	// Type of the integration (API, Marid, Prometheus, etc). The full list of options can be found here.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// It is required if type is Webhook. This is the url Opsgenie will be sending request to.
	// +kubebuilder:validation:Optional
	WebhookURL *string `json:"webhookUrl,omitempty" tf:"webhook_url,omitempty"`
}

type ApiIntegrationRespondersObservation struct {
}

type ApiIntegrationRespondersParameters struct {

	// The id of the responder.
	// +crossplane:generate:reference:type=Team
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Team to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Team to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`

	// Type of the integration (API, Marid, Prometheus, etc). The full list of options can be found here.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ApiIntegrationSpec defines the desired state of ApiIntegration
type ApiIntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ApiIntegrationParameters `json:"forProvider"`
}

// ApiIntegrationStatus defines the observed state of ApiIntegration.
type ApiIntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApiIntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ApiIntegration is the Schema for the ApiIntegrations API. Manages an API Integration within Opsgenie.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opsgenie}
type ApiIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ApiIntegrationSpec   `json:"spec"`
	Status            ApiIntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApiIntegrationList contains a list of ApiIntegrations
type ApiIntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApiIntegration `json:"items"`
}

// Repository type metadata.
var (
	ApiIntegration_Kind             = "ApiIntegration"
	ApiIntegration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ApiIntegration_Kind}.String()
	ApiIntegration_KindAPIVersion   = ApiIntegration_Kind + "." + CRDGroupVersion.String()
	ApiIntegration_GroupVersionKind = CRDGroupVersion.WithKind(ApiIntegration_Kind)
)

func init() {
	SchemeBuilder.Register(&ApiIntegration{}, &ApiIntegrationList{})
}
