# Terraform Docs
# https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/team

apiVersion: opsgenie.upbound.io/v1alpha1
kind: ApiIntegration
metadata:
  name: integration-name
spec:
  forProvider:
    # Optional, This parameter is for specifying whether the integration will be enabled or not.
    # Default: true
    enabled: true

    # Required, Name of the integration. Name must be unique for each integration.
    name: opgenie-integration-name

    # Optional, Type of the integration (API, Marid, Prometheus, etc).
    # The full list of options can be found here.
    # https://support.atlassian.com/opsgenie/docs/integration-types-to-be-used-with-the-api/
    type: Prometheus

    # Optional, This parameter is for configuring the write access of integration.
    # If write access is restricted, the integration will not be authorized to write within any domain.
    # Default: true.
    allowWriteAccess: false

    # Optional,If enabled, the integration will ignore recipients sent in request payloads.
    # Default: false.
    ignoreRespondersFromPayload: false

    # Optional, If enabled, notifications that come from alerts will be suppressed.
    # Default: false.
    suppressNotifications: false

    # Optional, Owner team id reference of the integration.
    # Is mutually exclusive with responders.
    # Use "ownerTeamId" to statically write the team uuid.
    ownerTeamIdRef:
      name: team-name

    # Optional, User, schedule, teams or escalation names to calculate which users will receive the notifications of the alert.
    # Is mutually exclusive with ownerTeamIdRef.
    responders:
      - idRef:
          name: team-name
        # Must be lower case.
        type: team

      # Crossplane does not support cross-resource refernces of multiple types.
      # Therefore it is not possible to reference below user, schedule or escalation, but you can statically add them.
      # https://github.com/crossplane/crossplane-runtime/issues/350

      # - id: <some-uuid>
      #   type: user

      # - id: <some-uuid>
      #   type: schedule

      # - id: <some-uuid>
      #   type:  escalation

    # Optional, It is required if type is Webhook.
    # This is the url Opsgenie will be sending request to.
    webhookUrl: https://api.example.com/v1

  providerConfigRef:
    name: default
