# Terraform Docs
# https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/alert_policy

apiVersion: opsgenie.upbound.io/v1alpha1
kind: AlertPolicy
metadata:
  name: alert-policy-name
spec:
  forProvider:
    # Optional, This parameter is for specifying whether the policy will be enabled or not.
    # Default: true
    enabled: true

    # Required, Name of the integration. Name must be unique for each integration.
    name: alert-policy-name

    # Optional, Id of team that this policy belongs to.
    teamIdRef:
      name: team-name

    # Optional, Description of the policy. This can be max 512 characters.
    policyDescription: Some description

    # Required: A alert filter which will be applied.
    # This filter can be empty: filter {} - this means match-all. This is a block, structure is documented below.
    filter:
      # Optional, A filter type, supported types are: match-all, match-any-condition, match-all-conditions. Default: match-all
      - type: match-all

        # Optional, Conditions applied to filter. This is a block, structure is documented below.
        conditions:
          # Required, Specifies which alert field will be used in condition.
          # Possible values are message, alias, description, source, entity, tags, actions, details, extra-properties, recipients, teams, priority.
          - field: extra-properties

            # Required: It is the operation that will be executed for the given field and key.
            # Possible operations are matches, contains, starts-with, ends-with, equals, contains-key, contains-value, greater-than, less-than, is-empty, equals-ignore-whitespace.
            operation: matches

            # Optional, If field is set as extra-properties, key could be used for key-value pair.
            key: some-value

            # Optinal, Indicates behaviour of the given operation. Default: false
            not: false

            # Optional, User defined value that will be compared with alert field according to the operation. Default: empty string
            expectedValue: some-value

            # Optional, Order of the condition in conditions list.
            order: 1

    # Optional, Time restrictions specified in this field must be met for this policy to work.
    timeRestriction:
      # Required, Defines if restriction should apply daily on given hours or on certain days and hours.
      # Possible values are: time-of-day, weekday-and-time-of-day
      - type: weekday-and-time-of-day

        # Optinal, List of days and hours definitions for field type = weekday-and-time-of-day.
        restrictions:
          # Required, Starting day of restriction (eg. monday)
          - startDay: monday

            # Required, Starting hour of restriction on defined startDay
            startHour: 7

            # Required, Staring minute of restriction on defined startHour
            startMin: 15

            # Required, Ending day of restriction (eg. wednesday)
            endDay: friday

            # Required, Ending hour of restriction on defined endDay
            endHour: 16

            # Required, Ending minute of restriction on defined endHour
            endMin: 0

            # Required, Starting day of restriction (eg. monday)
          - startDay: saturday

            # Required, Starting hour of restriction on defined startDay
            startHour: 10

            # Required, Staring minute of restriction on defined startHour
            startMin: 0

            # Required, Ending day of restriction (eg. wednesday)
            endDay: sunday

            # Required, Ending hour of restriction on defined endDay
            endHour: 14

            # Required, Ending minute of restriction on defined endHour
            endMin: 0

      # Example on using "time-of-day" combined with "restriction".
      # Even though "restriction" is an array, it's not possible to use more than one object.
      # - type: time-of-day

      #   # Optional, A definition of hourly definition applied daily, this has to be used with combination: type = time-of-day.
      #   restriction:
      #     # Required, Starting hour of restriction.
      #   - startHour: 7

      #     # Required, Ending hour of restriction.
      #     endHour: 16

      #     # Required, Staring minute of restriction on defined startHour
      #     startMin: 00

      #     # Required, Ending minute of restriction on defined endHour
      #     endMin: 0

    # Required, Message of the alerts.
    message: "{{message}}"

    # Optinal,  It will trigger other modify policies if set to true. Default: false
    continuePolicy: false

    # Optional, Alias of the alert. You can use {{alias}} to refer to the original alias. Default: {{alias}}.
    alias: "{{alias}}"

    # Optional, Description of the alert. You can use {{description}} to refer to the original alert description. Default: {{description}}
    alertDescription: "{{description}}"

    # Optional, Entity field of the alert. You can use {{entity}} to refer to the original entity. Default: {{entity}}
    entity: "{{entity}}"

    # Optional, Source field of the alert. You can use {{source}} to refer to the original source. Default: {{source}}
    source: "{{source}}"

    # Optional, If set to true, policy will ignore the original actions of the alert. Default: false
    ignoreOriginalActions: false

    # Optional, If set to true, policy will ignore the original responders of the alert. Default: false
    ignoreOriginalResponders: false

    # Optional, Responders to add to the alerts original responders value as a list of teams, users or the reserved word none or all.
    # If ignoreOriginalResponders field is set to true, this will replace the original responders.
    # The possible values for responders are: user, team.
    responders:
      # Required, Type of responder. Acceptable values are: user or team.
      - type: team

        # Optional, Name of the responder.
        name: some-name

        # Required, ID of the responder.
        # Only "type: team" has support for id referencing by name, else use the "id" property with a static ID.
        idRef:
          name: team-name

        # id: some-static-id

        # Optional, Username of the responder.
        username: some-username

    # Optional, If set to true, policy will ignore the original tags of the alert. Default: false
    ignoreOriginalTags: false

    # Optional, Actions to add to the alerts original actions value as a list of strings.
    # If ignoreOriginalActions field is set to true, this will replace the original actions.
    actions:
      - some-custom-action

    # Optional, Tags to add to the alerts original tags value as a list of strings.
    # If ignoreOriginalResponders field is set to true, this will replace the original responders.
    tags:
      - some-extra-tag

    # Optional, Priority of the alert. Should be one of P1, P2, P3, P4, or P5.
    priority: P3

  providerConfigRef:
    name: default
