# ====================================================================================
# Setup Project

include ../../../build/makelib/common.mk

# ====================================================================================
#  Options

include ../../../build/makelib/imagelight.mk

# ====================================================================================
# Targets

img.publish:
	@$(INFO) Skipping image publish for $(IMAGE)
	@echo Publish is deferred to xpkg machinery
	@$(OK) Image publish skipped for $(IMAGE)

img.build:
	@$(INFO) docker build $(IMAGE):$(VERSION)
	@cp Dockerfile $(IMAGE_TEMP_DIR) || $(FAIL)
	@cp -R ../../../package $(IMAGE_TEMP_DIR) || $(FAIL)
	@cd $(IMAGE_TEMP_DIR) && find package -type f -name '*.yaml' -exec cat {} >> 'package.yaml' \; -exec printf '\n---\n' \; || $(FAIL)
	@docker buildx build --load \
		--platform $(IMAGE_PLATFORMS) \
		-t $(IMAGE) $(IMAGE_TEMP_DIR) || $(FAIL)
	@docker tag $(IMAGE) "$(IMAGE):$(VERSION)" || $(FAIL)
	@$(OK) Finished the docker build
